### ISSUE TITLE
Only works with x, y axis

### ISSUE THREAD

**Issue by burritobill** [antonpantev/unity-movement-ai#8]
It would make sense to be able to change axis from x,y to x,z for simple 3d games.

**Comment by sturdyspoon** [comment]
Yes it would make sense. The [dev](/antonpantev/unity-movement-ai/tree/dev) branch of this project is much farther along than master and already has x,z for 3D.

A number of people already use the dev branch instead of master so its pretty stable, but I'm not quite ready to merge all those changes into master.

**Comment by sturdyspoon** [comment]
I have merged the 3D code into master finally.
